name: fl_my_awesome
description: "A new Flutter project."
publish_to: 'none' #

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #UI
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.3.2
  fluttertoast: ^8.2.12
  flutter_svg: ^2.2.0
  image_picker: ^1.2.1
  camera: ^0.11.3
  image: ^4.5.4

  # Formatting
  intl: ^0.20.2
  mask_text_input_formatter: ^2.9.0

  # Animation
  animate_do: ^4.2.0
  lottie: ^3.3.1

  # Networking
  dartz: ^0.10.1
  http: ^1.4.0
  http_interceptor: ^2.0.0
  logger: ^2.5.0

  # GetX
  get: ^4.7.2
  get_storage: ^2.1.1

  # Device
  local_auth: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  assets:
    - assets/images/
    - assets/icons/
    - assets/lotties/
#    - assets/html/
#    - assets/texts/

  uses-material-design: true
